name: Build GGUFs

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install huggingface-cli
        run: |
          curl -LsSf https://hf.co/cli/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Download llama.cpp
        run: git clone https://github.com/ggml-org/llama.cpp

      - name: Cache llama.cpp build
        id: cache-llama
        uses: actions/cache@v4
        with:
          path: llama.cpp/build
          key: llama-cpp-build-${{ runner.os }}

      - name: Build llama.cpp (incremental)
        run: |
          cd llama.cpp
          cmake -B build
          cmake --build build --config Release -j $(nproc)

      - name: Create output directory
        run: mkdir -p $GITHUB_WORKSPACE/gguf
      
      - name: Install Python dependencies for conversion
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install --index-strategy unsafe-best-match -r $GITHUB_WORKSPACE/llama.cpp/requirements.txt
          uv pip install --upgrade transformers
          
      - name: Download model from Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf download bryce-hoehn/Qwen3.5-18B-REAP-A3B-Coding \
            --token $HF_TOKEN \
            --local-dir ./model \

      - name: Convert model to F16 GGUF
        run: |
          source .venv/bin/activate
          ls $GITHUB_WORKSPACE/llama.cpp
          uv run "$GITHUB_WORKSPACE/llama.cpp/convert_hf_to_gguf.py" \
            "$GITHUB_WORKSPACE/model" \
            --outfile "$GITHUB_WORKSPACE/Qwen3.5-18B-REAP-A3B-Coding-F16.gguf" \
            --outtype f16

      - name: Build quants
        run: |
          QUANTS=(
            "Q2_K" "Q3_K_M" "Q4_0" "Q4_1" "Q4_K_M" "Q5_0" "Q5_1" "Q5_K_M" "Q6_K" "Q8_0"
          )
          for quant in "${QUANTS[@]}"; do
            echo "Quantizing to $quant ..."
            "$GITHUB_WORKSPACE/llama.cpp/build/bin/llama-quantize" \
              /home/runner/work/Qwen3.5-18B-REAP-A3B-Coding/Qwen3.5-18B-REAP-A3B-Coding/Qwen3.5-18B-REAP-A3B-Coding-F16.gguf \
              $GITHUB_WORKSPACE/gguf/Qwen3.5-18B-REAP-A3B-Coding-${quant}.gguf \
              ${quant}
            echo "Uploading Qwen3.5-18B-REAP-A3B-Coding-${quant}.gguf"
            hf upload \
              --token $HF_TOKEN \
              Flagstone8878/Qwen3.5-18B-REAP-A3B-Coding-GGUF \
              $GITHUB_WORKSPACE/gguf/Qwen3.5-18B-REAP-A3B-Coding-${quant}.gguf \
              --repo-type model
            rm -rf $GITHUB_WORKSPACE/gguf/Qwen3.5-18B-REAP-A3B-Coding-${quant}.gguf
          done
